language: python
python:
  - "2.7"

# safelist
branches:
  only:
  - 17.1.4
  - 17.1.5
  - 17.1.6
  - 17.2.1
  - 17.2.2
  - 17.2.3
  - 17.2.4
  - 17.2.5
  - 17.2.6
  - 17.2.7
  - 17.2.8
  - 17.2.9
  - 17.2.10

# command to install dependencies
install:
- pip install pytest pyyaml requests pyparsing paramiko avisdk pycrypto ecdsa pyOpenssl nose-html-reporting nose-testconfig ConfigParser xlsxwriter jinja2 pandas openpyxl appdirs pexpect xlrd unittest2 networkx vcrpy pytest-cov pytest-xdist
- export PYTHONPATH=$PWD/python/
- echo $PYTHONPATH


# command to execute unit tests
script:

- pytest ./python/avi/sdk/utils/test/test_api_utils.py -vvvv --color=yes
- pytest ./python/avi/migrationtools/ace_converter/test/test_modules.py -vvvv --color=yes
- pytest ./python/avi/migrationtools/netscaler_converter/test/test_migrationtool.py -m travis --config ./python/avi/migrationtools/test/common/config.yaml -vvvv  --color=yes
- pytest ./python/avi/migrationtools/f5_converter/test/test_migrationtool.py -vvvv -m travis --config ./python/avi/migrationtools/test/common/config.yaml --color=yes
- pytest --cov=./python/avi/sdk/test ./python/avi/sdk/test/test_avi_api.py -m travis --config ./python/avi/sdk/test/test_api.cfg --cov-fail-under=80

