language: python
python:
  - "2.7"

# safelist
branches:
  only:
  - master
  - 17.1.4
  - 17.1.5
  - 17.1.6
  - 17.2.1
  - 17.2.2
  - 17.2.3
  - 17.2.4


# command to install dependencies
install:
- pip install pytest pyyaml requests pyparsing paramiko avisdk pycrypto ecdsa pyOpenssl nose-html-reporting nose-testconfig ConfigParser xlsxwriter jinja2 pandas openpyxl appdirs pexpect xlrd unittest2 networkx
- export PYTHONPATH=$PWD/python/
- echo $PYTHONPATH


# command to execute unit tests
script:
- pytest ./python/avi/sdk/utils/test/test_api_utils.py -vvvv --color=yes
- pytest ./python/avi/migrationtools/ace_converter/test/test_modules.py -vvvv --color=yes
- pytest ./python/avi/migrationtools/netscaler_converter/test/test_migrationtool.py -m travis --config ./python/avi/migrationtools/test/common/config.yaml -vvvv  --color=yes
- pytest ./python/avi/migrationtools/f5_converter/test/test_migrationtool.py -vvvv -m travis --config ./python/avi/migrationtools/test/common/config.yaml --color=yes
